[tox]
minversion=2.3.1
envlist = py39,py310,py311,py312,py313,py314,black
isolated_build = True

[testenv]
deps =
    black == 25.1.0
    pytest
commands =
    pytest tests/

[testenv:black]
commands =
    black --check .

[testenv:pycroscope]
deps =
    pycroscope == 0.12.0
commands =
    # Need recent pip for PEP 660-based editable installs.
    pip install --upgrade pip
    # Need an editable install so pycroscope imports the right version
    # of ast_decompiler.
    pip install -e .
    pycroscope --config-file=pyproject.toml ast_decompiler/ tests/

[testenv:fuzz]
skip_install = True
deps =
    # Skip in CI, it runs forever.
    # atheris
    coverage
    hypothesmith
commands =
    pip install -e .[d]
    coverage erase
    coverage run fuzz.py
    coverage report

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, black, pycroscope
    3.14-dev: py314
